name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: stalordtest  # e.g., stalordregistry
  IMAGE_NAME: fastapiapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7400181F2AF14E239BC25B54675655C0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_88BBDEAAA0B947938CD0E29F8F3C8CD5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E17FF599DDE0428F9CE3B2E70075EF70 }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
