name: Build, Push Docker Image, and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: stalordtest
  IMAGE_NAME: fastapiapp
  CLUSTER_NAME: stalordaks      # Replace with your AKS cluster name
  RESOURCE_GROUP: stalordrg     # Replace with your AKS resource group
  NAMESPACE: default

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build and Push Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

      - name: Deploy to AKS
        run: |
          kubectl apply -f ./k8s/deployment.yaml
          kubectl apply -f ./k8s/service.yaml
