# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ghatest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://stalordtest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b84c5d1d7f744d95a22764d80cab9787 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6614302587e641b4bbddfe0d8c4a8de5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: stalordtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b84c5d1d7f744d95a22764d80cab9787 }}/fastapiapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ghatest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1c2d8dfd7da746058880d3e9fd98c6f4 }}
        images: 'stalordtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b84c5d1d7f744d95a22764d80cab9787 }}/fastapiapp:${{ github.sha }}'